{
    'name': 'MiS XLS Reports',
    'version': '13.0.1',
    'summary': "XLS Reports",
    'description': "XLS Reports for stock and others",
    'category': 'Warehouse',
    'author': 'mindinfosys.com',
    'maintainer': 'mindinfosys.com',
    'company': 'mindinfosys.com',
    'website': 'http://www.mindinfosys.com',
    'depends': [
                'base',
                'stock',
                'sale',
                'purchase',
                ],
    'data': [
            'views/wizard_view.xml',
            'views/action_manager.xml',
            ],
#    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'auto_install': False,
}
