{
    "name": """POS: show product qty""",
    "summary": """Adds available quantity at products in POS""",
    "category": "Point Of Sale",
    "images": [],
    "version": "13.0.1.1.0",
    "application": False,
    "author": "Sananaz Mansuri",
    "website": "odoo.com",
    'license': 'Other proprietary',
    "depends": ["point_of_sale", "stock"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["data.xml", "views/views.xml"],
    "qweb": ["static/src/xml/pos.xml"],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
